#!/usr/bin/bash
set -e

echo this broke, since it needs ./a.out in the foreground
exit 1

function restart {
	if [ -n "$PID" ]; then
		echo "killing $PID"
		kill -9 $PID
	fi
	./a.out &
	PID=$!
	echo "started $PID"
}

function loop {
	while true; do
		inotifywait -e close_write patch || true;
		echo needs restart;
		echo d;
	done
}

function cleanup() {
	echo cleanup
	if [ -n "$PID" ]; then
		echo "killing $PID"
		kill -9 $PID
	fi
	exit 1
}
trap cleanup SIGINT

loop &

while true; do
	( echo $BASHPID; kill -SIGSTOP $BASHPID; echo start ) &
	PID=$!
	echo "PID is $PID"
	jobs
	fg %2
	sleep 2
done

