char patch_contents[] = ""
                        "[vfo1]\n"
                        "type=pulse12\n"
                        "output=0.3\n"
                        "attack=0.03\n"
                        "decay=0.2\n"
                        "sustain=0.0\n"
                        "release=0.0\n"
                        "\n"
                        "[vfo2]\n"
                        "type=sine\n"
                        "output=1.0\n"
                        "attack=0.2\n"
                        "release=0.8\n"
                        "sustain=0.4\n"
                        "decay=0.2\n";
