char patch_contents[] = ""
                        "[vfo1]\n"
                        "type=pulse12\n"
                        "output=0.3\n"
                        "attack=0.03\n"
                        "decay=0.2\n"
                        "sustain=0.0\n"
                        "release=0.0\n"
                        "\n"
                        "[vfo2]\n"
                        "type=sine\n"
                        "output=1.0\n"
                        "attack=0.2\n"
                        "release=0.8\n"
                        "sustain=0.4\n"
                        "decay=0.2\n"
                        "\n"
                        "[vfo3]\n"
                        "type=square\n"
                        "output=0.4\n"
                        "attack=0.2\n"
                        "release=0.8\n"
                        "sustain=0.4\n"
                        "decay=0.2\n"
                        "amp_input=lfo1\n"
                        "amp_input_m=1.0\n"
                        "\n"
                        "[lfo1]\n"
                        "type=triangle\n"
                        "freq=0.3\n"
                        "\n"
                        "\n"
                        "# [vfo3]\n"
                        "# type=sine\n"
                        "# freq_m=0.99\n"
                        "# output=1.0\n"
                        "# attack=0.2\n"
                        "# release=0.8\n"
                        "# sustain=0.4\n"
                        "# decay=0.2\n"
                        "# amp_input=lfo3\n"
                        "# phase_input=lfo4\n"
                        "# phase_input_m=0.03\n"
                        "#\n"
                        "# [vfo4]\n"
                        "# type=sine\n"
                        "# freq_m=1.01\n"
                        "# output=1.0\n"
                        "# attack=0.2\n"
                        "# release=0.8\n"
                        "# sustain=0.4\n"
                        "# decay=0.2\n"
                        "# amp_input=lfo4\n"
                        "# phase_input=lfo3\n"
                        "# phase_input_m=0.03\n"
                        "#\n"
                        "# [lfo3]\n"
                        "# type=random\n"
                        "# freq=3.0\n"
                        "#\n"
                        "# [lfo4]\n"
                        "# type=random\n"
                        "# freq=3.0\n";
