char patch_contents[] = ""
                        "[vfo1]\n"
                        "type=sine\n"
                        "output=1.0\n"
                        "attack=0.01\n"
                        "decay=20.0 # TODO, should this be exponential decay? the software only supports linear right now.\n"
                        "sustain=0.0\n"
                        "release=0.05\n"
                        "\n"
                        "\n"
                        "[vfo2]\n"
                        "type=sine\n"
                        "freq_m=0.5\n"
                        "output=0.7\n"
                        "attack=0.01\n"
                        "decay=20.0\n"
                        "sustain=0.0\n"
                        "release=0.05\n";
